name: medview3d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.20
  - matplotlib=3.5.1
  - nibabel=3.2
  - scipy=1.8
  - scikit-image=0.19
  - tk=8.6
  - pillow=9.0
  - pyqt=5
  - pip
  - pip:
    - tk3d 